name: Daily Commit Board

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: main
          persist-credentials: true

      - name: Set up branch tracking
        run: git branch --set-upstream-to=origin/main main || true

      - name: Set up Git config
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Make a daily commit
        run: |
          date=$(date)
          echo "Last updated on $date" > last-updated.txt
          git add last-updated.txt
          git commit -m "Daily update on $date" || echo "No changes to commit"
          git push
